### ISSUE TITLE
Pack resources to a single file

### ISSUE THREAD

**Issue by Berrysoft** [Uni-Gal/Ayaka#56]
Now we simplify put all files on the disk, and try to find them at runtime. It is not suitable for deployment.

We plan to take steps one by one.

- [x] Don't check files' existance through WASI fs. #57 
- [x] Use `tar` as the pack format. #57 
- [x] Resource override rules. #63 
- [ ] Add compression?

**Comment by Berrysoft** [comment]
We don't need compression up to now.
